version: "3.3"

services:
  frontend:
    container_name: container-frontend
    image: compose-frontend:homolog
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:80"
    volumes:
      - .:/app
