version: "3.3"

services:
  frontend:
    container_name: container-frontend
    image: compose-frontend:homolog
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8305:80" # Mapeando a porta 8305 do host para a porta 80 do contêiner
    volumes:
      - .:/app
